[[order]]

[lifecycle]
version = "0.21.12"

[build]
image = "ghcr.io/atls/stack-node:build"

[run]
[[run.images]]
image = "ghcr.io/atls/stack-node:run"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[[extensions]]
id = "tech.atls.extensions.curl"
uri = "docker://ghcr.io/atls/buildpack-extension-curl:0.0.1"

[[extensions]]
id = "tech.atls.extensions.htop"
uri = "docker://ghcr.io/atls/buildpack-extension-htop:0.0.1"

[[extensions]]
id = "tech.atls.extensions.graphql-hive"
uri = "docker://ghcr.io/atls/buildpack-extension-graphql-hive:0.0.1"

[[order-extensions]]
[[order-extensions.group]]
id = "tech.atls.extensions.curl"

[[order-extensions.group]]
id = "tech.atls.extensions.htop"

[[order-extensions.group]]
id = "tech.atls.extensions.graphql-hive"

# Deprecated
[stack]
id = "tech.atls.stacks.node"
run-image = "ghcr.io/atls/stack-node:run"
build-image = "ghcr.io/atls/stack-node:build"
