compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

globalFolder: ../.yarn/berry

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  atls:
    npmRegistryServer: "https://registry.npmjs.org"

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.cjs
