api = "0.6"

[buildpack]
id = "tech.atlantislab.buildpacks.yarn-install"
version = "0.0.5"
name = "Yarn Install Buildpack"

[metadata]
include_files = ["dist", "bin/build", "bin/detect", "buildpack.toml"]
pre_package = "yarn build"

[[stacks]]
id = "tech.atlantislab.stacks.node"

[[stacks]]
id = "tech.atlantislab.stacks.node-static"

[[stacks]]
id = "tech.atlantislab.stacks.operator"
