api = "0.10"

[buildpack]
id = "tech.atlantislab.buildpacks.yarn-workspace-start"
version = "0.1.1"
name = "Yarn Workspace Start Buildpack"

[metadata]
include_files = ["dist", "bin/build", "bin/detect", "buildpack.toml"]

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
