name: Release Please GitHub release

on:
  workflow_run:
    workflows:
      - Docker release
    branches:
      - master
    types:
      - completed

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: release-please-github-release
  cancel-in-progress: false

jobs:
  release-please:
    name: Release Please GitHub release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub releases
        uses: googleapis/release-please-action@v4.4.1
        with:
          token: ${{ secrets.PAT_token }}
          target-branch: master
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-github-pull-request: true
